sudo: false
language: node_js

cashe: npm 
node_js:
  - '14.15.0'

before_install: 
  - npm install
install: travis_retry pip install myawesomepackage
  
before_script:
  - npm test
after_success: npm run coverage

  
