sudo: false
language: node_js
services:
  - mongodb
cashe: npm 
node_js:
  - '14.15.0'

script:
  -npm run test
  - npm run build
  - npm run coverage
install:
  - npm install

after_success:
  - npm run coverage

  
